package models

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func Test_GetUserPrincipleNameFromToken(t *testing.T) {
	sut := GetUserPrincipleNameFromToken

	_, err := sut("invalid-token")
	assert.Error(t, err)

	/* The test JWT token in the next test is generated by the following commented code
	cl := jwt.MapClaims{"upn": "radix"}
	ts := jwt.NewWithClaims(jwt.SigningMethodES256, &cl)
	k, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	tokenstring, _ := ts.SignedString(k)
	fmt.Println(tokenstring)
	*/
	upn, _ := sut("eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cG4iOiJyYWRpeCJ9.dEWdnb6optaGXBKJg3TlWfxLvkzNUSujiozgWAzODwOjdTD0YYufowJ3xxrg79IJxHCI6UZi5cHEbFih5ZH2Bw")
	assert.Equal(t, "radix", upn)
}
